name: tester

on: 
  workflow_dispatch:
    pull_request:
      push:
        branches:
          - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4.6.0
      - name: Install requriements
        run: pip install -r requriements.txt
      - name: Run tests
        run: pytest